Bash cleanup

diff --git a/yt-playlist-sync b/yt-playlist-sync
--- a/yt-playlist-sync
+++ b/yt-playlist-sync
@@ -1,69 +1,55 @@
 #!/bin/bash
 
-
-function err {
-    echo "ERROR: $@"
+#FUNCTIONS
+function err 
+{
+	printf "$0 [ERROR]: %s\n" "$1" >&2
+	if [[ "$2" == "help" ]]
+	then
+		help
+		exit "$3"
+	else
+		exit "$2"
+	fi
 }
 
-function help {
-    echo "Usage:"
-    echo "    yt-playlist-sync PLAYLIST_PATH PLAYLIST_URL"
+function help 
+{
+    printf "$0 [USAGE]: yt-playlist-sync PLAYLIST_PATH PLAYLIST_URL\n"
 }
 
-
-#PERSONAL DEFAULTS
-plUrl="https://www.youtube.com/playlist?list=PLOoJ3WlgcZEyUhfpaLKzngtxOh2aV__ye"
-plPath=/home/salamon/down/music/watchLaterHistory-sync
+#KEY VARIABLES
 youParsePath="youParse/youParse.py"
-
-if [[ $1 == "" || $2 == "" ]]; then
-    err "Expecting 2 arguments"
-    help
-    exit 1
-fi
-
-plPath="$1"
-plUrl="$2"
-
-if [[ ! -d "$plPath" ]]; then
-    err "Directory does not exist - $plPath"
-    help
-    exit 2
-fi
-
-
 localUrls="$plPath/.urls"
 remoteUrls="$plPath/.urls-remote"
 diffUrls="$plPath/.urls-diff"
+plPath="$1"
+plUrl="$2"
 
+#INPUT VERIFICATION
+[[ "$#" -ne 2 ]] && err "Expecting 2 arguments" "help" 1
 
-if [[ ! -f "$localUrls" ]]; then
-    touch "$localUrls"
+[[ ! -d "$plPath" ]] && err "Directory does not exist - $plPath" "help" 2
+
+[[ ! -f "$localUrls" ]] && touch "$localUrls"
+
+if ! python3 "$youParsePath" "$plUrl" | sort > "$remoteUrls"
+then
+    err "Youtube playlist url is not vaild - $plUrl" "help" 3
 fi
 
-if ! python3 "$youParsePath" "$plUrl" | sort > "$remoteUrls"; then
-    err "Youtube playlist url is not vaild - $plUrl"
-    help
-    exit 3
-fi
-    
-
-tmpFile=`mktemp /tmp/yt-playlist-sync-XXX.tmp`
-cat "$localUrls" | sort > "$tmpFile"
-cat "$tmpFile" > "$localUrls"
-rm "$tmpFile"
-
+#CORE
+cat "$localUrls" | sort | tee "/dev/null" "$localUrls"
 comm -13 "$localUrls" "$remoteUrls" > "$diffUrls"
-
-echo "Downloading `cat $diffUrls | wc -l` new songs!"
+printf "Downloading `cat $diffUrls | wc -l` new songs!\n"
 
 cnt=0
 while read u; do
-    echo "Downloading $u"
+    printf "Downloading %s\n" "$u"
     if youtube-dl --audio-format mp3 -x -o "$plPath/%(title)s.%(ext)s" "$u"
     then
         echo "Success!"
-        echo "$u" >> "$localUrls"
+        printf "$u\n" >> "$localUrls"
         cnt=$(($cnt+1))
         # delete all webm files from previous runs after first success
         # keeps progress between two conscutive runs
@@ -75,6 +61,6 @@ while read u; do
     fi
 done < "$diffUrls"
 
-echo "Downloaded $cnt out of `cat $diffUrls | wc -l` new songs!"
+printf "Downloaded $cnt out of `cat $diffUrls | wc -l` new songs!"
 
-
+exit 0
